#!/bin/sh
#
# Create a new working directory in the current directory

prog=$(basename $0)

die() {
	echo >&2 "$@"
	exit 1
}

USAGE="$prog <branch> [defconfig]"

branch="$1"
base=$PWD
defconfig=$2

if test -z $branch
then
	die "usage: $USAGE"
fi

# Make new directory for branch
git-new-workdir $META_ROOT/.git $base/kernel $branch &&
mkdir $base/kobj &&

# Copy optional defconfig to the kobj directory
test -f "$defconfig" &&
cp $defconfig kobj/.config

ln -s $(readlink -f $META_ROOT/initrds) initrds
