#!/bin/sh

prog=$(basename $0)
USAGE="$prog <arch> [initrd]"

die() {
	printf >&2 "%s\n" "$@"
	exit 1
}

check_initrd() {
	if ! test -f "../initrds/$initrd"
	then
		echo >&2 "fatal: missing initrd '$initrd'"
		echo >&2 "Available initrds:"
		for x in ../initrds/*
		do
			printf >&2 "  %s\n" "${x#../initrds/}"
		done
		exit 1
	fi
}

if test -z "$1"
then
	die "usage: $USAGE"
fi

image=zImage
pagesize=2048
cmdline=
base=
initrd=

case "$1" in
g1 | 7201 | 7201a)
	cmdline="console=ttyMSM2,115200,n8"
	base=0x10000000
	;;
7x30 | 7630 | 7230)
	cmdline="console=ttyMSM1,115200,n8"
	base=0x200000
	pagesize=4096
	;;
8660 | 8x60)
	cmdline="console=hvc0"
	base=0x40200000
	;;
8960)
	cmdline="console=hvc0"
	base=0x80200000
	;;
*)
	die "Unknown architecture $1"
	;;
esac

while test $# != 0
do
	case "$1" in
	--kernel|--kernel=*)
		case "$#,$1" in
		*,*=*)
			kernel=`expr "z$1" : 'z-[^=]*=\(.*\)'` ;;
		1,*)
			die "bad" ;;
		*)
			kernel="$2"
			shift ;;
		esac
		;;
	--cmdline|--cmdline=*)
		case "$#,$1" in
		*,*=*)
			cmdline=`expr "z$1" : 'z-[^=]*=\(.*\)'` ;;
		1,*)
			die "bad" ;;
		*)
			cmdline="$2"
			shift ;;
		esac
		;;
	--base|--base=*)
		case "$#,$1" in
		*,*=*)
			base=`expr "z$1" : 'z-[^=]*=\(.*\)'` ;;
		1,*)
			die "bad" ;;
		*)
			base="$2"
			shift ;;
		esac
		;;
	*)
		initrd="$1"
		;;
	esac
	shift
done

image=arch/arm/boot/$image
initrd="${initrd:-initrd.gz}"

test -f ../kobj/$image || die "Can't find $image. Build a kernel?"
check_initrd

mkbootimg --kernel ../kobj/$image \
	--ramdisk ../initrds/$initrd \
	--cmdline "$cmdline" \
	--base $base \
	--pagesize $pagesize \
	--output ../boot.img &&
echo "Packaged $(readlink -f ../boot.img)"
